---

- name: install dns server
  yum:
    name: bind
    state: present

- name: copy bind config to remote host
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640
    backup: yes

- name: copy dns record to remote host
  template:
    src: example.zone.j2
    dest: /var/named/example.zone
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: copy dns reverse record to remote host
  template:
    src: example.reverse.j2
    dest: /var/named/example.reverse
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: Enable and Restart DNS Server
